"""Initial Migration

Revision ID: 4e9dfa29b768
Revises: 33ede96b831b
Create Date: 2021-05-30 18:33:16.119399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9dfa29b768'
down_revision = '33ede96b831b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('user', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
