"""empty message

Revision ID: 83716ffafecd
Revises: 34a6a8ffcd3f
Create Date: 2021-05-22 15:50:26.792037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83716ffafecd'
down_revision = '34a6a8ffcd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dept_name', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
