"""Initial migration.

Revision ID: b4dbf395ebc3
Revises: 
Create Date: 2021-05-13 16:25:05.577153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4dbf395ebc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpu', sa.String(length=150), nullable=True),
    sa.Column('gpu', sa.String(length=150), nullable=True),
    sa.Column('ram', sa.String(length=150), nullable=True),
    sa.Column('odd', sa.String(length=150), nullable=True),
    sa.Column('avr_ups', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spec')
    # ### end Alembic commands ###
