"""Initial Migration

Revision ID: b70c946821e4
Revises: 463d64d8a60a
Create Date: 2021-05-28 10:34:18.811581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70c946821e4'
down_revision = '463d64d8a60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('brand', sa.String(length=150), nullable=True),
    sa.Column('serial_number', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('item_type', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('remarks', sa.String(length=150), nullable=True),
    sa.Column('image', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=150), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=True),
    sa.Column('isApprove', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('item', 'approval')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('approval', sa.INTEGER(), nullable=True))
    op.drop_table('item_approval')
    # ### end Alembic commands ###
