"""Initial Migration

Revision ID: b795922775cc
Revises: 4e9dfa29b768
Create Date: 2021-05-30 21:57:47.239343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b795922775cc'
down_revision = '4e9dfa29b768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'date')
    # ### end Alembic commands ###
