"""empty message

Revision ID: dc2ae77215a2
Revises: 83716ffafecd
Create Date: 2021-05-22 16:39:01.671838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2ae77215a2'
down_revision = '83716ffafecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('approval', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'approval')
    # ### end Alembic commands ###
